server:
  port: 8081

github:
  bucket:
    # 仓库所属的用户名
    user: "Evan-Sukhoi"
    # 仓库名称
    repository: "ImageHost"
    # access Token
    access-token: "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"
    url: "https://cdn.jsdelivr.net/gh/${github.bucket.user}/${github.bucket.repository}/"
    api: "https://api.github.com/repos/${github.bucket.user}/${github.bucket.repository}/contents/"


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ooad?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT
    username: root
    password: lh23
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: true
  error:
    include-message: always
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    username: 1916853516@qq.com
    password: null
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
    port: 465

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB


mybatis-plus:
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #https://www.cnblogs.com/zhaodalei/p/16850870.html
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  mapper-locations: classpath*:/dao/**/*.xml

# 文件上传保存路径
upload-dir: backend/main/src/main/resources/static



