server:
  port: 8081

github:
  bucket:
    # 仓库所属的用户名
    user: "Evan-Sukhoi"
    # 仓库名称
    repository: "ImageHost"
    # access Token
    access-token: "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"
    url: "https://cdn.jsdelivr.net/gh/${github.bucket.user}/${github.bucket.repository}/"
    api: "https://api.github.com/repos/${github.bucket.user}/${github.bucket.repository}/contents/"


spring:
  jackson:
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/ooad?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 223844
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: true
  error:
    include-message: always
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    username: 1916853516@qq.com
    password: null
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
    port: 465

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB


mybatis-plus:
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #https://www.cnblogs.com/zhaodalei/p/16850870.html
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  mapper-locations: classpath*:/dao/**/*.xml

# 文件上传保存路径
upload-dir: backend/main/src/main/resources/static

# 支付宝配置
alipay:
  alipay.app-id: "9021000132655689"
  alipay.private-key: "MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCHCzuCGFcbG5g9MLVnA2KJLJyHdwEkpNwVaDdoiQEge+pgWar1mWyV9+FCrTO3UbgteucsyGBU/GtV92Ot/eG1iJyoMgk9yol56xaNhXNtnEX7sNAbAZUNWA1MDPblzIj0aF1MaRJ3RzsZ8kOqCFhp4KtOi/CuqpdY2pU35btEiwsuKetMsBrYado4z76mmq0pHSSgdLgr+JSWHryd2grV2OdV/c8CjmAz7KZKhe0tih/OuE2MwYxCurMXCk0aFJkWs3GAXJ/2DRgtDckqXiTIjxwd4c9GkIcfffHnSITiBpH/rA0wsA3VnYDnNGrCkZlg6CLrSKm3UauRO3zrHQzFAgMBAAECggEAN4WtvMpHHfUVfasGGklw/NcjsCqEhM1nU0Ha7hbOKM3pyh1zxbCDzZDxw5k0lx15LPHIFEh6GtcBRoIFMKceYqW9SwXveMFKDp9SUXNZxuomd9n1ZfUblDXsmaUG6epTMLGsElts5S+bJArQORtfRoDBzfSJSzcGLNkJ2saQXRh4hT6U8KRUJXj5l9tL7YdEVrnDJCr200cLXFxQXS3FcuY6YAq/aOao2VC9fJU3GmVAESfXyb5KhFoiyL6TdEVDMETZbyNeJXUFtGaQZe3D5xYRDUncvu+mLUIX8vzIZRYpZg1QtrxlkLGy0dC3jJmfSjb1S0iTICiyL3IH5XZtQQKBgQDHiZeuCSMjVqouSyHMuiEseXZvjNZB0+2+5KDRwPJPBat5I8x/rvBwfdvVvkQMP/p584yO2reosHRxVTSGB5UrqsOVSWq1V3lO1PCMzGqd1FbA9yqaJkgKggPEJKD4ECOqBrqnfUWZhqK0gloYU3G6CBWCtWj4gqNgiWcZdAtJ9QKBgQCtQcCI/i64dg/A5fwes+x+F6zFJxg+egmc0UZ2s3YWk+qvOgoFBiCh2iJ/YRHCh2x9ikz12gu/pvEqhO5pUckXsMeWyFtuF/o0Nw7pE/d7KjRE9qH7ehms0sFgRBsdVpuUKd2PztzZ3LEOu8B57RDhlMon3t3MMz92a2flL1DlkQKBgQCOmKrYCdmdoIqf6Ltv5jhc4zSbhWd8xapquFKhc6T2ihO/z7COMwPLMHaRKpbQtkwXKNDzKiUEHY4pi/2sJvEYssFxB3WFwMyFZLG/vToYLq4M2tYMMX1cXQu5+X87p7UFBigQF/tMOyY9n8YpCkEE9FADCAfLSPjevXL7gq2qnQKBgQCPEarR9UPTYvqjSccl+2GgxiAPNbdZcCEb89yCDLPI9SBozj6T43ly7dRq51dpEbdO+7ONmR72hf7EI71UDwtFmt9V7eFCSl58W7LeWXSVqkY7ZIZiSXOGOQsiWVsioPAcK24gYKwS46D6D6RjipXUEa/VuL3i77bKLOtAYBAnYQKBgQCSUxfAsN1JImGSb4uxK3tMhs4vGSnu61EygS+b74WumyXMeYKndeeN0eFUsU2/ACXW7FpMdhvhjraPaoibO2rzXWxTyhg30Vo6LOe//y0yswUW1E6OlUMpjVgzfM0oWO/qU2RTP64DJIqs/7MSTMTpq+cG5XVKn23LFDJ2U5netw=="
  alipay.public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAotXvliZl2UEZ5OSIYt/Zk0oe7Mz+u1JlIKONf2FOrhC+BbuGZ+4NgHa9hQAYBMajykHhKywYl6UgqsxfCQCGG4QSlVTUVO5/GWL5YkHeSnIpl1tZAdpk9+BCaCG6jAugBsOx3p6K3hB5en91NXloYvtf5thI8axFnu5qbQcSkl3dbV02sqaFna2upuxVUjY7H7vvakwF8dTamuNxf+mhbhtbuqXkqs1+l51rKxV9Z4aohVv9TCDUCX8dBrVc1eWaXdaoCRv66zNkahzwxkKLYiy7eArcu/o6fU9fgY9As5qFf6mlupXC9/Itd/TYQl4Cc1x+Txdl8BG1K9PESO+dowIDAQAB"
  alipay.notify-url: "https://openapi.alipaydev.com/gateway.do"


