server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ooad?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT
    username: root
    password: 223844
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: true
  error:
    include-message: always
  data:
    redis:
      host: localhost
      port: 6379

mybatis-plus:
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #https://www.cnblogs.com/zhaodalei/p/16850870.html
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  mapper-locations: classpath*:/dao/**/*.xml
