spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ooad?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: lh23
    driver-class-name: com.mysql.cj.jdbc.Driver